POST http://localhost:3000/api/mail/send
Content-Type: application/json

{
  "to": "juanpabloruizbre@gmail.com",
  "subject": "Correo de prueba local",
  "text": "Hola! Este es un correo de pruebas."
}
