### Crear producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "description": "Cheeseburger",
  "price": 5.99,
  "image": "https://example.com/cheeseburger.jpg",
  "categoryId": "f7247199-81ec-4296-a44a-4da401162dda",
  "ingredientIds": ["<uuid-ingrediente-1>", "<uuid-ingrediente-2>"],
  "promotionIds": ["<uuid-promocion-1>"]
}

### Actualizar producto
PUT http://localhost:3000/api/products/<uuid-del-producto>
Content-Type: application/json

{
  "description": "Cheeseburger Deluxe",
  "price": 6.99,
  "image": "https://example.com/cheeseburger-deluxe.jpg",
  "categoryId": "f7247199-81ec-4296-a44a-4da401162dda",
  "ingredientIds": ["<uuid-ingrediente-1>", "<uuid-ingrediente-3>"],
  "promotionIds": ["<uuid-promocion-2>"]
}

### Obtener todos los productos
GET http://localhost:3000/api/products

### Obtener producto por id
GET http://localhost:3000/api/products/<uuid-del-producto>

### Eliminar producto
DELETE http://localhost:3000/api/products/<uuid-del-producto>
